import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { FiHeart, FiHome, FiUser, FiSearch, FiShoppingBag } from "react-icons/fi";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nike",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Link href={"/"}>Home <FiHome/> </Link>
        <Link href={"/shop"}> Shop <FiSearch/> </Link>
        <Link href={"/favourites"}>Favourite <FiHeart/></Link>
        <Link href={"/bag"}>Bag <FiShoppingBag/></Link>
        <Link href={"/profile"}>Login <FiUser/></Link>
        {children}
      </body>
    </html>
  );
}
