import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/components/nav";
import { Suspense } from "react";
import { FavoriteProvider, CartProvider } from "@/utils/Contexts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nike",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartProvider>
        <FavoriteProvider>
        <NavBar/>
        <Suspense fallback={<GlobalLoading />}>
       <div className="w-full sm:max-w-xl lg:max-w-2xl mx-auto p-2"> {children} </div>
       </Suspense>
       </FavoriteProvider>
       </CartProvider>
      </body>
    </html>
  );
}



function GlobalLoading() {
  return (
    <div className="flex items-center justify-center h-screen">
      <p className="text-gray-500 animate-pulse text-lg">Loading page...</p>
    </div>
  );
}